version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Ebonding-Partner-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wj9b31yw0uzwq"
s3_prefix = "Ebonding-Partner--sam-app"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
